version: '3'

services:
  ri-synonym-service:
    build: .
    image: sdokara/ri-synonym-service:latest
    container_name: ri-synonym-service
    ports:
      - ${HTTP_PORT:-8080}:8080
    environment:
      - JAVA_OPTS
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-production}
    command: --spring.profiles.active=${SPRING_PROFILES_ACTIVE:-production}
    restart: ${DC_RESTART_POLICY:-unless-stopped}
